export type Colors =
  | 'transparent'
  | 'primary'
  | 'primaryStart'
  | 'primaryStop'
  | 'secondaryLight'
  | 'secondaryDark'
  | 'black'
  | 'white'
  | 'grey1'
  | 'grey2'
  | 'grey3'
  | 'grey4'
  | 'grey5'
  | 'grey6'
  | 'grey7'
  | 'grey8'
  | 'grey9'
  | 'success'
  | 'warningLight'
  | 'warningDark'
  | 'errorLight'
  | 'errorDark'
  | 'blue'
  | 'red'
  | 'orange'
  | 'self-color'
  | `primary/${number}`
  | `primaryStart/${number}`
  | `primaryStop/${number}`
  | `secondaryLight/${number}`
  | `secondaryDark/${number}`
  | `black/${number}`
  | `white/${number}`
  | `grey1/${number}`
  | `grey2/${number}`
  | `grey3/${number}`
  | `grey4/${number}`
  | `grey5/${number}`
  | `grey6/${number}`
  | `grey7/${number}`
  | `grey8/${number}`
  | `grey9/${number}`
  | `success/${number}`
  | `warningLight/${number}`
  | `warningDark/${number}`
  | `errorLight/${number}`
  | `errorDark/${number}`
  | `blue-${number}`
  | `red-${number}`
  | `orange-${number}`;
