compressionLevel: mixed

enableGlobalCache: false

enableColors: true


nodeLinker: node-modules

injectEnvironmentFiles: [
  ".env.local?",
  ".env.development.local?",
  ".env?"
]

checksumBehavior: update
