FROM node:lts

# Create app directory
WORKDIR /usr/src/ewa

COPY package*.json ./

RUN npm install

COPY . .
RUN npm run bootstrap
RUN npm run tsc:ui
RUN npm run tsc:sdk
RUN npm run pack:ui-apps
RUN npm run build:sdk

EXPOSE 9001 8131
CMD [ "npm", "run", "start:feed-app" ]
