[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  headers = {X-From = "Netlify"}

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' cloudflare.com *.cloudflare.com unpkg.com *.akasha.network *.ethereum.world *.walletconnect.org *.infura.io https://* wss://*; img-src https: data: blob:"

