export const mockTrendingTags = {
  searchTags: [
    {
      name: 'test',
      totalPosts: 7,
    },
    {
      name: 'newtestingtag',
      totalPosts: 2,
    },
    {
      name: 'tagsss',
      totalPosts: 2,
    },
    {
      name: 'riptwitter',
      totalPosts: 1,
    },
    {
      name: 'testing',
      totalPosts: 1,
    },
    {
      name: 'newtag1',
      totalPosts: 1,
    },
    {
      name: 'needaverylongtagtotestthings',
      totalPosts: 1,
    },
    {
      name: 'thursday',
      totalPosts: 1,
    },
    {
      name: 'heheheh',
      totalPosts: 0,
    },
    {
      name: 'newtag',
      totalPosts: 0,
    },
    {
      name: 'tag',
      totalPosts: 0,
    },
  ],
};

export const mockTrendingProfiles = {
  searchProfiles: [
    {
      pubKey: 'bbaareie2zhdat2ttqslkwon4pesnsb7djg45kzww2i6filzfkkshe24edq',
      name: null,
      userName: 'gicu',
      avatar: null,
      coverImage: null,
      description: null,
      ethAddress: '0xdE6Ec620D22aA2fc0A30d268a46C971DB6EAA229',
      totalPosts: '4',
      totalFollowers: 1,
      totalFollowing: 0,
      totalInterests: 0,
    },
    {
      pubKey: 'bbaareibgzgkmk5gvyj46osgfoio5fgljqfu5kwfn4jvzxvitlhzkv3nndu',
      name: null,
      userName: 'zero',
      avatar: null,
      coverImage: null,
      description: null,
      ethAddress: '0xA2F0aBB180185724fD615D23FF5e1AEf2afEf3B2',
      totalPosts: '0',
      totalFollowers: 1,
      totalFollowing: 0,
      totalInterests: 0,
    },
    {
      pubKey: 'bbaareib3aep4yf3woi4v2cde7op55yomqe2iri7vgma5zv6zgry4pwu2oa',
      name: null,
      userName: 'sssss',
      avatar: null,
      coverImage: null,
      description: null,
      ethAddress: '0x03DDaCC55Ef31bb6765D7e1CFBDD80fEaF2c15C8',
      totalPosts: '1',
      totalFollowers: 2,
      totalFollowing: 0,
      totalInterests: 0,
    },
    {
      pubKey: 'bbaareiggj4jpn4hszype7avuvoda2vhae6jgbowkqrx6hx7qtpmc4h7nme',
      name: null,
      userName: 'chicken',
      avatar: null,
      coverImage: null,
      description: null,
      ethAddress: '0x2c598d56dC985834F87e549Ace680c5946e569E6',
      totalPosts: '0',
      totalFollowers: 4,
      totalFollowing: 0,
      totalInterests: 0,
    },
    {
      pubKey: 'bbaareicd3rgekp3o3r64hwuozvwsoglyj7sbsic6nq5re45ymdbfeti2nq',
      name: null,
      userName: 'pssss',
      avatar: null,
      coverImage: null,
      description: null,
      ethAddress: '0x8EaFF34309342d184D40Ae0BA2Cc6C39bbc448C2',
      totalPosts: '0',
      totalFollowers: 1,
      totalFollowing: 0,
      totalInterests: 0,
    },
    {
      pubKey: 'bbaareiaf2pleir7wnkmihyy36qvt2m6m6pnegv5jldt5kz7glp46mh2jk4',
      name: 'lalala',
      userName: 'testing',
      avatar: null,
      coverImage: null,
      description: null,
      ethAddress: '0xea6bCEbC4aD892A0f744bbc7b7940293829322Bc',
      totalPosts: '1',
      totalFollowers: 0,
      totalFollowing: 0,
      totalInterests: 1,
    },
    {
      pubKey: 'bbaareic6eouhr646chfhb2e6cfdumdgsmdzgo4mxr5hvf2oboay5ru2uxi',
      name: 'MTEST',
      userName: 'smerakimaria',
      avatar: 'bafkreie37vhpgehizgdt77slhulotzqmp7yxeivci433h7izid7g5bitga',
      coverImage: 'bafkreicwmttfyi75kmkjhthvolvqhnirxe3yqypqc3bytihk4kvv3gduee',
      description: null,
      ethAddress: '0x08abE45e2bb306Eac696A2Da52F6E9684faBdc38',
      totalPosts: '3',
      totalFollowers: 0,
      totalFollowing: 1,
      totalInterests: 2,
    },
    {
      pubKey: 'bbaareiah42grrbw35cz6t2stic2sa7veno2bhvbij3xzc5xhplsrr75zym',
      name: null,
      userName: 'despacito',
      avatar: null,
      coverImage: null,
      description: null,
      ethAddress: '0x1C16DcaFbF474eb40D794e230D785c10d61f1B4d',
      totalPosts: '0',
      totalFollowers: 0,
      totalFollowing: 0,
      totalInterests: 0,
    },
    {
      pubKey: 'bbaareieeoufgnvi6izyvaalsv4tuvz6q3ccszygalvzyovsq3ukw6wbepe',
      name: 'testing',
      userName: 'heelloo',
      avatar: 'bafkreicikxus5pp5r5yi4sczeek3lfds3j3vpfyfe2yrrmr4krcyrmkmsi',
      coverImage: 'bafkreihxtnrksypbqyavl3hzu3vhuuzkx6bqwau5xq5zdl5smx22nuxx54',
      description: 'hello',
      ethAddress: '0x92Aa5CF1302883Ba0D470918a46033890Dd36048',
      totalPosts: '4',
      totalFollowers: 2,
      totalFollowing: 4,
      totalInterests: 0,
    },
    {
      pubKey: 'bbaareid3j3dllpd6ym2epxvuecxsplawxjqjzkjg7mhwx4h3blxpj4ubia',
      name: null,
      userName: 'test7acc',
      avatar: null,
      coverImage: null,
      description: null,
      ethAddress: '0xFC31185De616E0d6b7E4D9A7C13a16f0ca92d09e',
      totalPosts: '0',
      totalFollowers: 1,
      totalFollowing: 0,
      totalInterests: 0,
    },
    {
      pubKey: 'bbaareia25xp3bccmlvsvhgyvosezyf24r66eurfahsaw33tbu7mvlmeg2y',
      name: null,
      userName: 'awe',
      avatar: null,
      coverImage: null,
      description: null,
      ethAddress: '0xB2C2da7f22BE4828c0Efd711Eec38d5B55D13FE1',
      totalPosts: '0',
      totalFollowers: 2,
      totalFollowing: 0,
      totalInterests: 0,
    },
    {
      pubKey: 'bbaareiaencrbklkytr44hwgjxxbhdgcpc2y54w5otnclkhssjht36bdhoy',
      name: 'rainbow',
      userName: 'w0rks',
      avatar: null,
      coverImage: null,
      description: 'wallet connect rainbow wallet',
      ethAddress: '0x9bEdf2914F8AAf3290f423271C0Dd517DaD50E95',
      totalPosts: '0',
      totalFollowers: 4,
      totalFollowing: 2,
      totalInterests: 3,
    },
    {
      pubKey: 'bbaareigtmorcvl6etui553cbrtywxhbczgopnm4ygf3h75wt2o26hqqzxa',
      name: 'Akasha World',
      userName: 'gnosistestlul',
      avatar: 'bafkreie3c2fxvqjoywsbpebdgdtldtne5xd6bct7kejzqsqlxkuqawr55i',
      coverImage: null,
      description: null,
      ethAddress: '0x4941D523fa837A536B8bed834F6e6c807FAba24C',
      totalPosts: '7',
      totalFollowers: 5,
      totalFollowing: 1,
      totalInterests: 1,
    },
    {
      pubKey: 'bbaareigmmgasw3qnvptyzey2rhybji5xinvwyxniu43arjtuoo32b4gs5m',
      name: null,
      userName: 'loltroll',
      avatar: null,
      coverImage: null,
      description: null,
      ethAddress: '0x8bAB76d601208B4bda671deCe00Eeb648cDeA572',
      totalPosts: '0',
      totalFollowers: 4,
      totalFollowing: 1,
      totalInterests: 0,
    },
    {
      pubKey: 'bbaareibzwa2jvppqmtqur6tsm4zkg2ic3cqt65rpa5uizxwhyo5agdvyhe',
      name: null,
      userName: 'hehe',
      avatar: null,
      coverImage: null,
      description: null,
      ethAddress: '0x451782995D710622EdfBdEa795AA12067f53dfDc',
      totalPosts: '0',
      totalFollowers: 5,
      totalFollowing: 0,
      totalInterests: 0,
    },
    {
      pubKey: 'bbaareiavrkmgpjg5taxfb7hv62qets5xdivt3bq5yv3nolnntpiep2nazy',
      name: null,
      userName: 'openloginusert',
      avatar: null,
      coverImage: null,
      description: null,
      ethAddress: '0xD5DeE9c18d00cb6bc0c4D852be859A21718efE9d',
      totalPosts: '0',
      totalFollowers: 0,
      totalFollowing: 0,
      totalInterests: 0,
    },
    {
      pubKey: 'bbaareicjbwzokmey62ahg4yvngpvt76vzuxqpsoppxhycc4w63gftgw45a',
      name: null,
      userName: 'gigelchel',
      avatar: null,
      coverImage: null,
      description: null,
      ethAddress: '0xADE0510E72f60789DD17aAFc28629Ee4D9C0Ba72',
      totalPosts: '1',
      totalFollowers: 0,
      totalFollowing: 0,
      totalInterests: 0,
    },
    {
      pubKey: 'bbaareiaynqyedmlijgrvfxqvddmhpzdd7uqcgkmfhyox6lwotw3b46pcly',
      name: null,
      userName: 'tlog',
      avatar: null,
      coverImage: null,
      description: null,
      ethAddress: '0x6d4a14DFa2c08E6a1f1564425b091d539a96a4a8',
      totalPosts: '0',
      totalFollowers: 0,
      totalFollowing: 0,
      totalInterests: 0,
    },
    {
      pubKey: 'bbaareibk4k4fpllu46tuj62dhb5zgbzrwssj3rvq6luvqpjypoi6l6rumi',
      name: null,
      userName: 'character',
      avatar: null,
      coverImage: null,
      description: null,
      ethAddress: '0x64D4512E3C413feee9d37678A960d75bD8959d3b',
      totalPosts: '0',
      totalFollowers: 0,
      totalFollowing: 0,
      totalInterests: 0,
    },
    {
      pubKey: 'bbaareiau4wm4sm73ys46dyxkkxjln4asuwjbw7y4ws4kaw6hovxbayddou',
      name: 'Dumbledore',
      userName: 'dumbledore',
      avatar: null,
      coverImage: null,
      description: null,
      ethAddress: '0x33048ab11fcE0265DEFBc2988240f3A76ebb4c6a',
      totalPosts: '0',
      totalFollowers: 0,
      totalFollowing: 0,
      totalInterests: 0,
    },
  ],
};
