# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.3.1

jobs:
  setup:
    docker:
      # specify the version you desire here
      - image: cimg/node:18.16.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/akasha-world-framework

    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@9.5.1'
      - run:
          name: Install gcc
          command: 'sudo apt-get update -y && sudo apt-get install -y build-essential libsqlite3-dev'
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          keys:
            - dep-newest1-cache-v1-{{ checksum "yarn.lock" }}
            - dep-newest1-cache-v1
      - run:
          name: Install yarn packages
          command: |
            yarn cache clean
            yarn add @web3modal/ethers5@^3.3.2 -W
            yarn install
      - save_cache:
          paths:
            - node_modules
          key: dep-newest1-cache-v1-{{ checksum "yarn.lock" }}
      - run:
          name: Prepare continuation parameters
          command: |
            #TODO: exclude messaging, af-testing, hup-api, and app loader apps till their tsc and failing tests are fixed
            export AFFECTED_PROJECTS=$(npx nx print-affected --target=tsc --select=tasks.target.project --base=next --exclude='@akashaorg/app-messaging', '@akashaorg/af-testing', '@akashaorg/hub-api', '@akashaorg/ui-app-loader')
            export NUM_AFFECTED_PROJECTS=$(echo $AFFECTED_PROJECTS | sed 's/, /\n/g' | wc -l | xargs)

            echo '{ "affected-projects": "'$AFFECTED_PROJECTS'", "num-affected-projects": '$NUM_AFFECTED_PROJECTS' }' >> .circleci/continuation-params.json
      - continuation/continue:
          configuration_path: ./.circleci/continuation.yml
          parameters: ./.circleci/continuation-params.json

workflows:
  setup:
    jobs:
      - setup
