# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.3.1
  node: circleci/node@5.2.0

jobs:
  setup:
    docker:
      # specify the version you desire here
      - image: cimg/base:stable

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/akasha-core

    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - node/install:
          node-version: '20.11.0'
          yarn-version: '4.1.1'
      - run: node --version
      - run: corepack enable
      - run: corepack prepare yarn@4.1.1 --activate
      - run: yarn --version
      - node/install-packages:
          check-cache: detect
          pkg-manager: yarn-berry
      - run:
          name: Prepare continuation parameters
          command: |
            #TODO: exclude messaging, af-testing, hup-api, and app loader apps till their tsc and failing tests are fixed
            export AFFECTED_PROJECTS=$(npx nx print-affected --target=tsc --select=tasks.target.project --base=next --exclude='@akashaorg/app-messaging', '@akashaorg/af-testing', '@akashaorg/hub-api', '@akashaorg/ui-app-loader')
            export NUM_AFFECTED_PROJECTS=$(echo $AFFECTED_PROJECTS | sed 's/, /\n/g' | wc -l | xargs)

            echo '{ "affected-projects": "'$AFFECTED_PROJECTS'", "num-affected-projects": '$NUM_AFFECTED_PROJECTS' }' >> .circleci/continuation-params.json
#      - continuation/continue:
#          configuration_path: ./.circleci/continuation.yml
#          parameters: ./.circleci/continuation-params.json

workflows:
  setup:
    jobs:
      - setup
