import * as React from 'react';
import { ITagData } from './tag-card';
import { IProfileData } from '../profile-cards/profile-widget-card';
export interface ICustomizeFeedCardProps {
  profiles: IProfileData[];
  tags: ITagData[];
  title1Label?: string;
  subtitle1Label?: string;
  subtitle1LaterLabel?: string;
  title2Label?: string;
  subtitle2Label?: string;
  searchLabel?: string;
  searchPlaceholderLabel?: string;
  cancelLabel?: string;
  nextStepLabel?: string;
  createMyFeedLabel?: string;
  subscribeLabel?: string;
  followLabel?: string;
  mentionsLabel?: string;
  postsLabel?: string;
  handleCreateFeed: () => void;
  handleFollow: (profileEthAddress: string) => void;
  handleUnfollow: (profileEthAddress: string) => void;
  handleSubscribe: (tagNAme: string) => void;
  handleUnsubscribe: (name: string) => void;
  className?: string;
  style?: React.CSSProperties;
}
declare const CustomizeFeedCard: React.FC<ICustomizeFeedCardProps>;
export { CustomizeFeedCard };
