export const SETTINGS_SERVICE = 'SETTINGS_SERVICE';
export const VALIDATOR_SERVICE_FACTORY = 'VALIDATOR_SERVICE_FACTORY';
export const CACHE_PROVIDER_FACTORY = 'CACHE_PROVIDER_FACTORY';
export const WEB3_SERVICE = 'WEB3_SERVICE';
export const IPFS_SERVICE = 'IPFS_SERVICE';
