import * as HeroIcons from '@heroicons/react/24/outline';

export type IconType =
  | keyof typeof HeroIcons
  | 'akasha'
  | 'alignCenter'
  | 'alignLeft'
  | 'alignRight'
  | 'alignJustify'
  | 'antenna'
  | 'boldAlt'
  | 'didKey'
  | 'discord'
  | 'eth'
  | 'faq'
  | 'github'
  | 'integrationAppCTA'
  | 'italic'
  | 'licensewtfpl'
  | 'licenseAllRights'
  | 'licenseAttribution'
  | 'licenseNoDerivatives'
  | 'licenseNoRights'
  | 'licenseNonCommercial'
  | 'licenseShareAlike'
  | 'licenseSomeRights'
  | 'listNumbered'
  | 'listBulleted'
  | 'metamask'
  | 'noEth'
  | 'shield'
  | 'solana'
  | 'strikethrough'
  | 'telegram'
  | 'text'
  | 'textcaseLower'
  | 'textcaseSentence'
  | 'textcaseUpper'
  | 'twitter'
  | 'underline'
  | 'vibe'
  | 'walletconnect'
  | 'widget'
  | 'following';
