const BASE_URL = process.env.MODERATION_API;

const BASE_REPORT_URL = `${BASE_URL}/reports`;
const BASE_STATUS_URL = `${BASE_URL}/status`;
const BASE_REASONS_URL = `${BASE_URL}/reasons`;
const BASE_DECISION_URL = `${BASE_URL}/decisions`;
const BASE_MODERATOR_URL = `${BASE_URL}/moderators/status`;

const DEFAULT_FETCH_TIMEOUT = 12000;

const PENDING_CACHE_KEY_PREFIX = 'PENDING';
const MODERATED_CACHE_KEY_PREFIX = 'MODERATED';
const MODERATION_COUNT_CACHE_KEY_PREFIX = 'COUNT';

const LOG_ITEMS_KEY = 'LOG_ITEMS';
const KEPT_ITEMS_KEY = 'KEPT_ITEMS';
const PENDING_ITEMS_KEY = 'PENDING_ITEMS';
const DELISTED_ITEMS_KEY = 'DELISTED_ITEMS';
const CHECK_MODERATOR_KEY = 'CHECK_MODERATOR';
const MODERATION_STATUS_KEY = 'MODERATION_STATUS';
const MODERATION_ITEM_FLAGS_KEY = 'MODERATION_ITEM_FLAGS';
const MODERATION_ITEMS_COUNT_KEY = 'MODERATION_ITEMS_COUNT';

const INJECTED_PROVIDER_KEY = 'INJECTED_PROVIDER';

const TOKEN_VALIDATION_KEY = 'TOKEN_VALIDATION';

export default {
  BASE_REPORT_URL,
  BASE_STATUS_URL,
  BASE_REASONS_URL,
  BASE_DECISION_URL,
  BASE_MODERATOR_URL,
  DEFAULT_FETCH_TIMEOUT,
  PENDING_CACHE_KEY_PREFIX,
  MODERATED_CACHE_KEY_PREFIX,
  MODERATION_COUNT_CACHE_KEY_PREFIX,
  LOG_ITEMS_KEY,
  KEPT_ITEMS_KEY,
  PENDING_ITEMS_KEY,
  DELISTED_ITEMS_KEY,
  CHECK_MODERATOR_KEY,
  MODERATION_STATUS_KEY,
  MODERATION_ITEM_FLAGS_KEY,
  MODERATION_ITEMS_COUNT_KEY,
  INJECTED_PROVIDER_KEY,
  TOKEN_VALIDATION_KEY,
};
