export const TAGS = [
  'ethereum',
  'bitcoin',
  'cryptocurrency',
  'blockchain',
  'crypto',
  'btc',
  'litecoin',
  'bitcoinmining',
  'eth',
  'money',
  'trading',
  'bitcoins',
  'bitcoinnews',
  'forex',
  'cryptocurrencies',
  'investment',
  'ripple',
  'cryptonews',
  'bitcoincash',
  'xrp',
  'cryptotrading',
  'coinbase',
  'bitcointrading',
  'bitcoinprice',
  'business',
  'investing',
  'binance',
  'invest',
  'entrepreneur',
  'bhfyp',
];

export const USERNAMES = [
  {
    name: 'John',
    userName: 'john',
    pubKey: ' 13131mknnksbshl',
    avatar: 'https://placebeard.it/480/480',
    description: 'hello',
    coverImage: 'blue',
    ethAddress: '0x000001131313142834',
  },
  {
    name: 'Alex',
    userName: 'alex',
    pubKey: ' 13131mknnksbsho',
    avatar: 'https://placebeard.it/480/480',
    description: 'hello world',
    coverImage: 'red',
    ethAddress: '0x000001131313142833',
  },
  {
    name: 'Zeno',
    userName: 'zeno',
    pubKey: ' 13131mknnksbshr',
    avatar: 'https://placebeard.it/480/480',
    description: 'nono',
    coverImage: 'blue',
    ethAddress: '0x000001131313342834',
  },
];
