version: '3.9'
services:
  graphql:
    build: .
    environment:
      - PORT=3113
    ports:
      - '3113:3113'
    logging:
      driver: "json-file"
      options:
        max-size: "15m"
        max-file: "3"
