interface AkashaWorldConfigExtensionInterface @loadModel(id: "kjzl6hvfrbw6c7k6iyw6s8gcf8givfrrjx13jpas057ucmbmwljdtxpt40a3vpd") {
    id: ID!
  }


  type AkashaApp @loadModel(id: "kjzl6hvfrbw6c60my2sbyqyt980u1jq26ci8m19d996qscgcg87kpwp447iu15p") {
    id: ID!
    worldConfigs: [AkashaWorldConfigExtensionInterface] @relationFrom(model: "AkashaWorldConfigExtensionInterface", property: "extensionID")
    worldsConfigsCount: Int! @relationCountFrom(model: "AkashaWorldConfigExtensionInterface", property: "extensionID")
  }

  interface AkashaWorldConfigInterface @loadModel(id: "kjzl6hvfrbw6c65njjzje95z9n2kb4mbjs85bzlytunkl2m2w10p4rcthpmw7zg") {
    id: ID!
  }

    interface AkashaWorldMetaInfoInterface @loadModel(id: "kjzl6hvfrbw6c5zvl21tkam3io2bk85tanc9hdbtkau1zwpaud8l9bj9rfaqhrd") {
    id: ID!
  }

  type AkashaWorldConfig @loadModel(id: "kjzl6hvfrbw6c7y848mgsxu0cc34alfejwfqjjwrkab99hms4xbbe57j1kx3pcz") {
    id: ID!
    extensions: [AkashaWorldConfigExtensionInterface] @relationFrom(model: "AkashaWorldConfigExtensionInterface", property: "worldConfigID")
  }


  type AkashaWorld @loadModel(id: "kjzl6hvfrbw6c5k0h7zbzuksfgxoqkd2u41i9n4skcqi09drkxskef3kaae35vd") {
    id: ID!
    configInfo: [AkashaWorldConfigInterface] @relationFrom(model: "AkashaWorldConfigInterface", property: "worldID")
    metaInfo: [AkashaWorldMetaInfoInterface] @relationFrom(model: "AkashaWorldMetaInfoInterface", property: "worldID")
  }
  