interface AkashaWorldConfigExtensionInterface @loadModel(id: "kjzl6hvfrbw6c7ig149oppeo7doizirlhwrnzvggifpcbpl2d5eppxknjzpxkzk") {
    id: ID!
  }


  type AkashaApp @loadModel(id: "kjzl6hvfrbw6c55lze6s2ab18ebzwg51e9q1xrw5uxl1pf3z10dg39lxruh7heo") {
    id: ID!
    worldConfigs: [AkashaWorldConfigExtensionInterface] @relationFrom(model: "AkashaWorldConfigExtensionInterface", property: "extensionID")
    worldsConfigsCount: Int! @relationCountFrom(model: "AkashaWorldConfigExtensionInterface", property: "extensionID")
  }

  interface AkashaWorldConfigInterface @loadModel(id: "kjzl6hvfrbw6c63gmxylppyl2rrl9vukj5b2wrm0yqs91gihepveef303bmw2gk") {
    id: ID!
  }

    interface AkashaWorldMetaInfoInterface @loadModel(id: "kjzl6hvfrbw6c7pnrxhwgq923dna7og4m49e00kur83qnb2f4sqrnl8lqrxla0g") {
    id: ID!
  }

  type AkashaWorldConfig @loadModel(id: "kjzl6hvfrbw6c9wucr3ebil6wafdf9sr6xfei8dvsb6lnw03iviitrb7b6ckbcp") {
    id: ID!
    extensions: [AkashaWorldConfigExtensionInterface] @relationFrom(model: "AkashaWorldConfigExtensionInterface", property: "worldConfigID")
  }


  type AkashaWorld @loadModel(id: "kjzl6hvfrbw6c6sw3lrslrc3tf60xh0dj28tz5v5v8osunjm51wuaptan3k50v2") {
    id: ID!
    configInfo: [AkashaWorldConfigInterface] @relationFrom(model: "AkashaWorldConfigInterface", property: "worldID")
    metaInfo: [AkashaWorldMetaInfoInterface] @relationFrom(model: "AkashaWorldMetaInfoInterface", property: "worldID")
  }
  