// This is an auto-generated file, do not edit manually
import type { RuntimeCompositeDefinition } from '@composedb/types';
export const definition: RuntimeCompositeDefinition = {
  models: {
    AkashaApp: {
      interface: false,
      implements: [],
      id: 'kjzl6hvfrbw6c6aw2o64rn4b02b2z2t9ehhe419zkk6pakvpzcf7nj9xdunzf4m',
      accountRelation: { type: 'list' },
    },
    AkashaAppRelease: {
      interface: false,
      implements: [],
      id: 'kjzl6hvfrbw6c5dwel0ej7ji6vedsbsqa2ll4tvb0spraw1ovj3i9jh0m4kr7cr',
      accountRelation: { type: 'list' },
    },
    AkashaAppsStream: {
      interface: false,
      implements: [],
      id: 'kjzl6hvfrbw6c75fx2h6k6llvytdqhku4ro6mpms052808fc9d0yxpadj18krfp',
      accountRelation: { type: 'list' },
    },
    AkashaBeam: {
      interface: false,
      implements: [],
      id: 'kjzl6hvfrbw6c81jn00de1kfzdjtdbbivos4k3f17wa4a0u45c2v26d3j1eve68',
      accountRelation: { type: 'list' },
    },
    AkashaBeamStream: {
      interface: false,
      implements: [],
      id: 'kjzl6hvfrbw6c81i8l2ygrazc002jwpdmmhkcmuflegol3s6n3rbq1xofw19uu4',
      accountRelation: { type: 'list' },
    },
    AkashaBlockStorage: {
      interface: false,
      implements: [],
      id: 'kjzl6hvfrbw6carv0txorpadrkxksas8dc2co00hlu6e0hb5n2u3fvp88gmgbc7',
      accountRelation: { type: 'list' },
    },
    AkashaContentBlock: {
      interface: false,
      implements: [],
      id: 'kjzl6hvfrbw6c9raeoa7g1c9s53pl91qhnk8pp0cxmjbj2ug2t7mmn8arhz3mth',
      accountRelation: { type: 'list' },
    },
    AkashaContentBlockStream: {
      interface: false,
      implements: [],
      id: 'kjzl6hvfrbw6c6ra9dowgimgcbpg2yzhaf5lrizr6ic1ey27sh1fc1xhmqmy7oz',
      accountRelation: { type: 'list' },
    },
    AkashaFollow: {
      interface: false,
      implements: [],
      id: 'kjzl6hvfrbw6ca3ixw4rn2ow7o3c1o2hykpld8tjqt4pbm0j026gvn65z8czzo7',
      accountRelation: { type: 'list' },
    },
    AkashaIndexedStream: {
      interface: false,
      implements: [],
      id: 'kjzl6hvfrbw6c69sh9txsx7m2eejww4jhyveyq9gzfrozf3d5ga4dzzcmuzhoym',
      accountRelation: { type: 'list' },
    },
    AkashaInterestsStream: {
      interface: false,
      implements: [],
      id: 'kjzl6hvfrbw6c83mlm8bapkawnjvnp606z0vpzvgtmzn2i5p637w6egb8hnh512',
      accountRelation: { type: 'list' },
    },
    AkashaProfile: {
      interface: false,
      implements: [],
      id: 'kjzl6hvfrbw6c862oulkrdvxh2yfbhc997f7ahqtjppj2ejg8too3j7jmu8gsno',
      accountRelation: { type: 'single' },
    },
    AkashaProfileInterests: {
      interface: false,
      implements: [],
      id: 'kjzl6hvfrbw6c95dq5wbg095i40ylzxkrxcrzhepdfv72vfwzalt311z4lfuyml',
      accountRelation: { type: 'single' },
    },
    AkashaProfileStream: {
      interface: false,
      implements: [],
      id: 'kjzl6hvfrbw6caq96g93040j8vgzdh6hpnhqiqx5d9srxmk2qgdvf1360jv60tk',
      accountRelation: { type: 'list' },
    },
    AkashaReflect: {
      interface: false,
      implements: [],
      id: 'kjzl6hvfrbw6c9az8glxdc257r0tgzkjxj01nhwxilaciiidaxwafw4023wimnp',
      accountRelation: { type: 'list' },
    },
    AkashaReflectStream: {
      interface: false,
      implements: [],
      id: 'kjzl6hvfrbw6can8iaw4svciosyhl40auo44n31eqqvjjplkdwpkkk5f103csgd',
      accountRelation: { type: 'list' },
    },
  },
  objects: {
    AkashaApp: {
      name: { type: 'string', required: true, immutable: false, indexed: true },
      licence: { type: 'string', required: true, immutable: false },
      keywords: {
        type: 'list',
        required: false,
        immutable: false,
        item: { type: 'string', required: false, immutable: false },
      },
      createdAt: { type: 'datetime', required: true, immutable: false, indexed: true },
      description: { type: 'string', required: true, immutable: false },
      displayName: { type: 'string', required: true, immutable: false, indexed: true },
      contributors: {
        type: 'list',
        required: false,
        immutable: false,
        item: { type: 'did', required: false, immutable: false },
      },
      applicationType: {
        type: 'reference',
        refType: 'enum',
        refName: 'AkashaAppApplicationType',
        required: false,
        immutable: false,
        indexed: true,
      },
      author: { type: 'view', viewType: 'documentAccount' },
      version: { type: 'view', viewType: 'documentVersion' },
      releases: {
        type: 'view',
        viewType: 'relation',
        relation: {
          source: 'queryConnection',
          model: 'kjzl6hvfrbw6c5dwel0ej7ji6vedsbsqa2ll4tvb0spraw1ovj3i9jh0m4kr7cr',
          property: 'applicationID',
        },
      },
      releasesCount: {
        type: 'view',
        viewType: 'relation',
        relation: {
          source: 'queryCount',
          model: 'kjzl6hvfrbw6c5dwel0ej7ji6vedsbsqa2ll4tvb0spraw1ovj3i9jh0m4kr7cr',
          property: 'applicationID',
        },
      },
    },
    AkashaAppRelease: {
      source: { type: 'cid', required: true, immutable: false },
      version: { type: 'string', required: true, immutable: false, indexed: true },
      createdAt: { type: 'datetime', required: true, immutable: false, indexed: true },
      applicationID: { type: 'streamid', required: true, immutable: false, indexed: true },
      application: {
        type: 'view',
        viewType: 'relation',
        relation: {
          source: 'document',
          model: 'kjzl6hvfrbw6c6aw2o64rn4b02b2z2t9ehhe419zkk6pakvpzcf7nj9xdunzf4m',
          property: 'applicationID',
        },
      },
    },
    AkashaAppsStream: {
      active: { type: 'boolean', required: true, immutable: false, indexed: true },
      status: {
        type: 'reference',
        refType: 'enum',
        refName: 'AkashaAppsStreamModerationStatus',
        required: false,
        immutable: false,
        indexed: true,
      },
      createdAt: { type: 'datetime', required: true, immutable: false, indexed: true },
      moderationID: { type: 'streamid', required: false, immutable: false, indexed: true },
      applicationID: { type: 'streamid', required: true, immutable: false, indexed: true },
      application: {
        type: 'view',
        viewType: 'relation',
        relation: {
          source: 'document',
          model: 'kjzl6hvfrbw6c6aw2o64rn4b02b2z2t9ehhe419zkk6pakvpzcf7nj9xdunzf4m',
          property: 'applicationID',
        },
      },
    },
    AkashaBeam: {
      nsfw: { type: 'boolean', required: false, immutable: false, indexed: true },
      tags: {
        type: 'list',
        required: false,
        immutable: false,
        item: {
          type: 'reference',
          refType: 'object',
          refName: 'AkashaBeamLabeled',
          required: false,
          immutable: false,
        },
      },
      active: { type: 'boolean', required: true, immutable: false, indexed: true },
      content: {
        type: 'list',
        required: true,
        immutable: false,
        item: {
          type: 'reference',
          refType: 'object',
          refName: 'AkashaBeamBlockRecord',
          required: true,
          immutable: false,
        },
      },
      mentions: {
        type: 'list',
        required: false,
        immutable: false,
        item: { type: 'did', required: false, immutable: false },
      },
      createdAt: { type: 'datetime', required: true, immutable: false, indexed: true },
      embeddedStream: {
        type: 'reference',
        refType: 'object',
        refName: 'AkashaBeamEmbeddedType',
        required: false,
        immutable: false,
      },
      author: { type: 'view', viewType: 'documentAccount' },
      version: { type: 'view', viewType: 'documentVersion' },
      reflections: {
        type: 'view',
        viewType: 'relation',
        relation: {
          source: 'queryConnection',
          model: 'kjzl6hvfrbw6c9az8glxdc257r0tgzkjxj01nhwxilaciiidaxwafw4023wimnp',
          property: 'beamID',
        },
      },
      reflectionsCount: {
        type: 'view',
        viewType: 'relation',
        relation: {
          source: 'queryCount',
          model: 'kjzl6hvfrbw6c9az8glxdc257r0tgzkjxj01nhwxilaciiidaxwafw4023wimnp',
          property: 'beamID',
        },
      },
    },
    AkashaBeamBlockRecord: {
      order: { type: 'integer', required: true, immutable: false },
      blockID: { type: 'streamid', required: true, immutable: false },
    },
    AkashaBeamEmbeddedType: {
      label: { type: 'string', required: true, immutable: false },
      embeddedID: { type: 'streamid', required: true, immutable: false },
    },
    AkashaBeamLabeled: {
      value: { type: 'string', required: true, immutable: false },
      labelType: { type: 'string', required: true, immutable: false },
    },
    AkashaBeamStream: {
      active: { type: 'boolean', required: true, immutable: false, indexed: true },
      beamID: { type: 'streamid', required: true, immutable: false, indexed: true },
      status: {
        type: 'reference',
        refType: 'enum',
        refName: 'AkashaBeamStreamModerationStatus',
        required: false,
        immutable: false,
        indexed: true,
      },
      createdAt: { type: 'datetime', required: true, immutable: false, indexed: true },
      moderationID: { type: 'streamid', required: false, immutable: false, indexed: true },
      beam: {
        type: 'view',
        viewType: 'relation',
        relation: {
          source: 'document',
          model: 'kjzl6hvfrbw6c81jn00de1kfzdjtdbbivos4k3f17wa4a0u45c2v26d3j1eve68',
          property: 'beamID',
        },
      },
    },
    AkashaBlockStorage: {
      kind: {
        type: 'reference',
        refType: 'enum',
        refName: 'AkashaBlockStorageBlockStorageDef',
        required: false,
        immutable: false,
        indexed: true,
      },
      active: { type: 'boolean', required: true, immutable: false, indexed: true },
      blockID: { type: 'streamid', required: true, immutable: false },
      content: {
        type: 'list',
        required: true,
        immutable: false,
        item: {
          type: 'reference',
          refType: 'object',
          refName: 'AkashaBlockStorageLabeledValue',
          required: true,
          immutable: false,
        },
      },
      createdAt: { type: 'datetime', required: true, immutable: false, indexed: true },
      appVersionID: { type: 'streamid', required: true, immutable: false },
      block: {
        type: 'view',
        viewType: 'relation',
        relation: {
          source: 'document',
          model: 'kjzl6hvfrbw6c9raeoa7g1c9s53pl91qhnk8pp0cxmjbj2ug2t7mmn8arhz3mth',
          property: 'blockID',
        },
      },
      author: { type: 'view', viewType: 'documentAccount' },
      version: { type: 'view', viewType: 'documentVersion' },
      appVersion: {
        type: 'view',
        viewType: 'relation',
        relation: {
          source: 'document',
          model: 'kjzl6hvfrbw6c5dwel0ej7ji6vedsbsqa2ll4tvb0spraw1ovj3i9jh0m4kr7cr',
          property: 'appVersionID',
        },
      },
    },
    AkashaBlockStorageLabeledValue: {
      label: { type: 'string', required: true, immutable: false },
      value: { type: 'string', required: true, immutable: false },
      propertyType: { type: 'string', required: true, immutable: false },
    },
    AkashaContentBlock: {
      kind: {
        type: 'reference',
        refType: 'enum',
        refName: 'AkashaContentBlockBlockDef',
        required: false,
        immutable: false,
        indexed: true,
      },
      nsfw: { type: 'boolean', required: false, immutable: false, indexed: true },
      active: { type: 'boolean', required: true, immutable: false, indexed: true },
      content: {
        type: 'list',
        required: true,
        immutable: false,
        item: {
          type: 'reference',
          refType: 'object',
          refName: 'AkashaContentBlockLabeledValue',
          required: true,
          immutable: false,
        },
      },
      createdAt: { type: 'datetime', required: true, immutable: false, indexed: true },
      appVersionID: { type: 'streamid', required: true, immutable: false, indexed: true },
      author: { type: 'view', viewType: 'documentAccount' },
      version: { type: 'view', viewType: 'documentVersion' },
      appVersion: {
        type: 'view',
        viewType: 'relation',
        relation: {
          source: 'document',
          model: 'kjzl6hvfrbw6c5dwel0ej7ji6vedsbsqa2ll4tvb0spraw1ovj3i9jh0m4kr7cr',
          property: 'appVersionID',
        },
      },
    },
    AkashaContentBlockLabeledValue: {
      label: { type: 'string', required: true, immutable: false },
      value: { type: 'string', required: true, immutable: false },
      propertyType: { type: 'string', required: true, immutable: false },
    },
    AkashaContentBlockStream: {
      active: { type: 'boolean', required: true, immutable: false, indexed: true },
      status: {
        type: 'reference',
        refType: 'enum',
        refName: 'AkashaContentBlockStreamModerationStatus',
        required: false,
        immutable: false,
        indexed: true,
      },
      blockID: { type: 'streamid', required: true, immutable: false, indexed: true },
      createdAt: { type: 'datetime', required: true, immutable: false, indexed: true },
      moderationID: { type: 'streamid', required: false, immutable: false, indexed: true },
      block: {
        type: 'view',
        viewType: 'relation',
        relation: {
          source: 'document',
          model: 'kjzl6hvfrbw6c9raeoa7g1c9s53pl91qhnk8pp0cxmjbj2ug2t7mmn8arhz3mth',
          property: 'blockID',
        },
      },
    },
    AkashaFollow: {
      profileID: { type: 'streamid', required: true, immutable: false, indexed: true },
      isFollowing: { type: 'boolean', required: true, immutable: false, indexed: true },
      did: { type: 'view', viewType: 'documentAccount' },
      profile: {
        type: 'view',
        viewType: 'relation',
        relation: {
          source: 'document',
          model: 'kjzl6hvfrbw6c862oulkrdvxh2yfbhc997f7ahqtjppj2ejg8too3j7jmu8gsno',
          property: 'profileID',
        },
      },
    },
    AkashaIndexedStream: {
      active: { type: 'boolean', required: true, immutable: false, indexed: true },
      status: {
        type: 'reference',
        refType: 'enum',
        refName: 'AkashaIndexedStreamModerationStatus',
        required: false,
        immutable: false,
        indexed: true,
      },
      stream: { type: 'streamid', required: true, immutable: false, indexed: true },
      createdAt: { type: 'datetime', required: true, immutable: false, indexed: true },
      indexType: { type: 'string', required: true, immutable: false, indexed: true },
      indexValue: { type: 'string', required: true, immutable: false, indexed: true },
      streamType: {
        type: 'reference',
        refType: 'enum',
        refName: 'AkashaIndexedStreamStreamType',
        required: false,
        immutable: false,
        indexed: true,
      },
      moderationID: { type: 'streamid', required: false, immutable: false, indexed: true },
    },
    AkashaInterestsStream: {
      value: { type: 'string', required: true, immutable: false, indexed: true },
      active: { type: 'boolean', required: true, immutable: false, indexed: true },
      status: {
        type: 'reference',
        refType: 'enum',
        refName: 'AkashaInterestsStreamModerationStatus',
        required: false,
        immutable: false,
        indexed: true,
      },
      createdAt: { type: 'datetime', required: true, immutable: false, indexed: true },
      labelType: { type: 'string', required: true, immutable: false, indexed: true },
      moderationID: { type: 'streamid', required: false, immutable: false, indexed: true },
    },
    AkashaProfile: {
      name: { type: 'string', required: true, immutable: false, indexed: true },
      nsfw: { type: 'boolean', required: false, immutable: false, indexed: true },
      links: {
        type: 'list',
        required: false,
        immutable: false,
        item: {
          type: 'reference',
          refType: 'object',
          refName: 'AkashaProfileLinkSource',
          required: false,
          immutable: false,
        },
      },
      avatar: {
        type: 'reference',
        refType: 'object',
        refName: 'AkashaProfileImageVersions',
        required: false,
        immutable: false,
      },
      createdAt: { type: 'datetime', required: true, immutable: false, indexed: true },
      background: {
        type: 'reference',
        refType: 'object',
        refName: 'AkashaProfileImageVersions',
        required: false,
        immutable: false,
      },
      description: { type: 'string', required: false, immutable: false },
      did: { type: 'view', viewType: 'documentAccount' },
      followers: {
        type: 'view',
        viewType: 'relation',
        relation: {
          source: 'queryConnection',
          model: 'kjzl6hvfrbw6ca3ixw4rn2ow7o3c1o2hykpld8tjqt4pbm0j026gvn65z8czzo7',
          property: 'profileID',
        },
      },
      followersCount: {
        type: 'view',
        viewType: 'relation',
        relation: {
          source: 'queryCount',
          model: 'kjzl6hvfrbw6ca3ixw4rn2ow7o3c1o2hykpld8tjqt4pbm0j026gvn65z8czzo7',
          property: 'profileID',
        },
      },
    },
    AkashaProfileImageSource: {
      src: { type: 'uri', required: true, immutable: false },
      width: { type: 'integer', required: true, immutable: false },
      height: { type: 'integer', required: true, immutable: false },
    },
    AkashaProfileImageVersions: {
      default: {
        type: 'reference',
        refType: 'object',
        refName: 'AkashaProfileImageSource',
        required: true,
        immutable: false,
      },
      alternatives: {
        type: 'list',
        required: false,
        immutable: false,
        item: {
          type: 'reference',
          refType: 'object',
          refName: 'AkashaProfileImageSource',
          required: false,
          immutable: false,
        },
      },
    },
    AkashaProfileInterests: {
      topics: {
        type: 'list',
        required: true,
        immutable: false,
        item: {
          type: 'reference',
          refType: 'object',
          refName: 'AkashaProfileInterestsLabeled',
          required: true,
          immutable: false,
        },
      },
      did: { type: 'view', viewType: 'documentAccount' },
    },
    AkashaProfileInterestsLabeled: {
      value: { type: 'string', required: true, immutable: false },
      labelType: { type: 'string', required: true, immutable: false },
    },
    AkashaProfileLinkSource: {
      href: { type: 'uri', required: true, immutable: false },
      label: { type: 'string', required: false, immutable: false },
    },
    AkashaProfileStream: {
      active: { type: 'boolean', required: true, immutable: false, indexed: true },
      status: {
        type: 'reference',
        refType: 'enum',
        refName: 'AkashaProfileStreamModerationStatus',
        required: false,
        immutable: false,
        indexed: true,
      },
      createdAt: { type: 'datetime', required: true, immutable: false, indexed: true },
      profileID: { type: 'streamid', required: true, immutable: false, indexed: true },
      moderationID: { type: 'streamid', required: false, immutable: false, indexed: true },
      profile: {
        type: 'view',
        viewType: 'relation',
        relation: {
          source: 'document',
          model: 'kjzl6hvfrbw6c862oulkrdvxh2yfbhc997f7ahqtjppj2ejg8too3j7jmu8gsno',
          property: 'profileID',
        },
      },
    },
    AkashaReflect: {
      nsfw: { type: 'boolean', required: false, immutable: false, indexed: true },
      tags: {
        type: 'list',
        required: false,
        immutable: false,
        item: { type: 'string', required: false, immutable: false },
      },
      active: { type: 'boolean', required: true, immutable: false, indexed: true },
      beamID: { type: 'streamid', required: true, immutable: false },
      content: {
        type: 'list',
        required: true,
        immutable: false,
        item: {
          type: 'reference',
          refType: 'object',
          refName: 'AkashaReflectProviderValue',
          required: true,
          immutable: false,
        },
      },
      isReply: { type: 'boolean', required: false, immutable: false, indexed: true },
      mentions: {
        type: 'list',
        required: false,
        immutable: false,
        item: { type: 'streamid', required: false, immutable: false },
      },
      createdAt: { type: 'datetime', required: true, immutable: false, indexed: true },
      reflection: { type: 'streamid', required: false, immutable: false, indexed: true },
      beam: {
        type: 'view',
        viewType: 'relation',
        relation: {
          source: 'document',
          model: 'kjzl6hvfrbw6c81jn00de1kfzdjtdbbivos4k3f17wa4a0u45c2v26d3j1eve68',
          property: 'beamID',
        },
      },
      author: { type: 'view', viewType: 'documentAccount' },
      version: { type: 'view', viewType: 'documentVersion' },
    },
    AkashaReflectProviderValue: {
      label: { type: 'string', required: true, immutable: false },
      value: { type: 'string', required: true, immutable: false },
      propertyType: { type: 'string', required: true, immutable: false },
    },
    AkashaReflectStream: {
      active: { type: 'boolean', required: true, immutable: false, indexed: true },
      beamID: { type: 'streamid', required: true, immutable: false, indexed: true },
      status: {
        type: 'reference',
        refType: 'enum',
        refName: 'AkashaReflectStreamModerationStatus',
        required: false,
        immutable: false,
        indexed: true,
      },
      createdAt: { type: 'datetime', required: true, immutable: false, indexed: true },
      moderationID: { type: 'streamid', required: false, immutable: false, indexed: true },
      reflectionID: { type: 'streamid', required: true, immutable: false, indexed: true },
      reflection: {
        type: 'view',
        viewType: 'relation',
        relation: {
          source: 'document',
          model: 'kjzl6hvfrbw6c9az8glxdc257r0tgzkjxj01nhwxilaciiidaxwafw4023wimnp',
          property: 'reflectionID',
        },
      },
    },
  },
  enums: {
    AkashaAppApplicationType: ['APP', 'PLUGIN', 'WIDGET', 'OTHER'],
    AkashaAppsStreamModerationStatus: ['REMOVED', 'IN_REVIEW', 'SUSPENDED', 'NSFW', 'OK', 'OTHER'],
    AkashaBeamStreamModerationStatus: ['REMOVED', 'IN_REVIEW', 'SUSPENDED', 'NSFW', 'OK', 'OTHER'],
    AkashaBlockStorageBlockStorageDef: ['TEXT', 'BOOL', 'EMOJI', 'FORM_DATA', 'OTHER'],
    AkashaContentBlockBlockDef: ['TEXT', 'FORM', 'OTHER'],
    AkashaContentBlockStreamModerationStatus: [
      'REMOVED',
      'IN_REVIEW',
      'SUSPENDED',
      'NSFW',
      'OK',
      'OTHER',
    ],
    AkashaIndexedStreamModerationStatus: [
      'REMOVED',
      'IN_REVIEW',
      'SUSPENDED',
      'NSFW',
      'OK',
      'OTHER',
    ],
    AkashaIndexedStreamStreamType: [
      'BEAM',
      'REFLECT',
      'PROFILE',
      'APP',
      'EXTENSION',
      'PLUGIN',
      'WIDGET',
      'OTHER',
    ],
    AkashaInterestsStreamModerationStatus: [
      'REMOVED',
      'IN_REVIEW',
      'SUSPENDED',
      'NSFW',
      'OK',
      'OTHER',
    ],
    AkashaProfileStreamModerationStatus: [
      'REMOVED',
      'IN_REVIEW',
      'SUSPENDED',
      'NSFW',
      'OK',
      'OTHER',
    ],
    AkashaReflectStreamModerationStatus: [
      'REMOVED',
      'IN_REVIEW',
      'SUSPENDED',
      'NSFW',
      'OK',
      'OTHER',
    ],
  },
  accountData: {
    akashaAppList: { type: 'connection', name: 'AkashaApp' },
    akashaAppReleaseList: { type: 'connection', name: 'AkashaAppRelease' },
    akashaAppsStreamList: { type: 'connection', name: 'AkashaAppsStream' },
    akashaBeamList: { type: 'connection', name: 'AkashaBeam' },
    akashaBeamStreamList: { type: 'connection', name: 'AkashaBeamStream' },
    akashaBlockStorageList: { type: 'connection', name: 'AkashaBlockStorage' },
    akashaContentBlockList: { type: 'connection', name: 'AkashaContentBlock' },
    akashaContentBlockStreamList: { type: 'connection', name: 'AkashaContentBlockStream' },
    akashaFollowList: { type: 'connection', name: 'AkashaFollow' },
    akashaIndexedStreamList: { type: 'connection', name: 'AkashaIndexedStream' },
    akashaInterestsStreamList: { type: 'connection', name: 'AkashaInterestsStream' },
    akashaProfile: { type: 'node', name: 'AkashaProfile' },
    akashaProfileInterests: { type: 'node', name: 'AkashaProfileInterests' },
    akashaProfileStreamList: { type: 'connection', name: 'AkashaProfileStream' },
    akashaReflectList: { type: 'connection', name: 'AkashaReflect' },
    akashaReflectStreamList: { type: 'connection', name: 'AkashaReflectStream' },
  },
};
