// This is an auto-generated file, do not edit manually
import type { RuntimeCompositeDefinition } from '@composedb/types';
export const definition: RuntimeCompositeDefinition = {
  models: {
    AkashaApp: {
      interface: false,
      implements: [],
      id: 'kjzl6hvfrbw6cb6pcdpdnrlau2rwz0gs5nddo3e5v578s4wstt2kpybrf11byzc',
      accountRelation: { type: 'set', fields: ['name'] },
    },
    AkashaAppRelease: {
      interface: false,
      implements: [],
      id: 'kjzl6hvfrbw6cb03csk8bxuw50irl6m8e0diylhi6euhs9by3ssazl8x5bxhgzj',
      accountRelation: { type: 'set', fields: ['applicationID', 'version'] },
    },
    AkashaAppsStream: {
      interface: false,
      implements: [],
      id: 'kjzl6hvfrbw6c74jj2x5ydoj22ol1srkn8ts5mm8j85svsjs58ff8pfwvvpirhf',
      accountRelation: { type: 'set', fields: ['applicationID'] },
    },
    AkashaBeam: {
      interface: false,
      implements: [],
      id: 'kjzl6hvfrbw6c81jn00de1kfzdjtdbbivos4k3f17wa4a0u45c2v26d3j1eve68',
      accountRelation: { type: 'list' },
    },
    AkashaBeamStream: {
      interface: false,
      implements: [],
      id: 'kjzl6hvfrbw6c64u60jzs9nsy8o2csa7cmr76c0cj1odymgqegeqfnbk25mcdse',
      accountRelation: { type: 'set', fields: ['beamID'] },
    },
    AkashaBlockStorage: {
      interface: false,
      implements: [],
      id: 'kjzl6hvfrbw6c7fp2g35zxltb1m63sbkallc5p9pzj2nx0zkomea0pwgusb7lv9',
      accountRelation: { type: 'set', fields: ['blockID'] },
    },
    AkashaContentBlock: {
      interface: false,
      implements: [],
      id: 'kjzl6hvfrbw6c7in46qz14j69433lcmldlxqsyrxvayimxaqd62w7wnhkv2p4vd',
      accountRelation: { type: 'list' },
    },
    AkashaContentBlockStream: {
      interface: false,
      implements: [],
      id: 'kjzl6hvfrbw6c67gv90zl68cu80l4bwnfvu4i8pk5zxke0pvp4y203cuaijqwus',
      accountRelation: { type: 'set', fields: ['blockID'] },
    },
    AkashaFollow: {
      interface: false,
      implements: [],
      id: 'kjzl6hvfrbw6c5jg1zwrvbcvembp7v15kejrry05o2gvv2r4xghzfn2uluglus3',
      accountRelation: { type: 'set', fields: ['profileID'] },
    },
    AkashaIndexedStream: {
      interface: false,
      implements: [],
      id: 'kjzl6hvfrbw6caxx4dsfzdbgghx2merc27jx8q1aj6knymqyfmlrhek55eia9eh',
      accountRelation: { type: 'set', fields: ['stream', 'indexType', 'indexValue'] },
    },
    AkashaInterestsStream: {
      interface: false,
      implements: [],
      id: 'kjzl6hvfrbw6c7con370lhawow0s9hiwrobxkfazyn8fdtzzhid6jytus7xb2tt',
      accountRelation: { type: 'set', fields: ['labelType', 'value'] },
    },
    AkashaProfile: {
      interface: false,
      implements: [],
      id: 'kjzl6hvfrbw6c862oulkrdvxh2yfbhc997f7ahqtjppj2ejg8too3j7jmu8gsno',
      accountRelation: { type: 'single' },
    },
    AkashaProfileInterests: {
      interface: false,
      implements: [],
      id: 'kjzl6hvfrbw6c95dq5wbg095i40ylzxkrxcrzhepdfv72vfwzalt311z4lfuyml',
      accountRelation: { type: 'single' },
    },
    AkashaProfileStream: {
      interface: false,
      implements: [],
      id: 'kjzl6hvfrbw6c7almx92k0txlkm2plbo8g8gttxc7koevln0xj9vk028q8f2ryz',
      accountRelation: { type: 'set', fields: ['profileID'] },
    },
    AkashaReflect: {
      interface: false,
      implements: [],
      id: 'kjzl6hvfrbw6c9az8glxdc257r0tgzkjxj01nhwxilaciiidaxwafw4023wimnp',
      accountRelation: { type: 'list' },
    },
    AkashaReflectStream: {
      interface: false,
      implements: [],
      id: 'kjzl6hvfrbw6c8d51y2m3h8ykuboig237w39abyg4uwynwz3lcg81523o1ss65j',
      accountRelation: { type: 'set', fields: ['reflectionID'] },
    },
  },
  objects: {
    AkashaApp: {
      name: { type: 'string', required: true, immutable: true, indexed: true },
      licence: { type: 'string', required: true, immutable: false },
      keywords: {
        type: 'list',
        required: false,
        immutable: false,
        item: { type: 'string', required: false, immutable: false },
      },
      createdAt: { type: 'datetime', required: true, immutable: false, indexed: true },
      description: { type: 'string', required: true, immutable: false },
      displayName: { type: 'string', required: true, immutable: false, indexed: true },
      contributors: {
        type: 'list',
        required: false,
        immutable: false,
        item: { type: 'did', required: false, immutable: false },
      },
      applicationType: {
        type: 'reference',
        refType: 'enum',
        refName: 'AkashaAppApplicationType',
        required: false,
        immutable: false,
        indexed: true,
      },
      author: { type: 'view', viewType: 'documentAccount' },
      version: { type: 'view', viewType: 'documentVersion' },
      releases: {
        type: 'view',
        viewType: 'relation',
        relation: {
          source: 'queryConnection',
          model: 'kjzl6hvfrbw6cb03csk8bxuw50irl6m8e0diylhi6euhs9by3ssazl8x5bxhgzj',
          property: 'applicationID',
        },
      },
      releasesCount: {
        type: 'view',
        viewType: 'relation',
        relation: {
          source: 'queryCount',
          model: 'kjzl6hvfrbw6cb03csk8bxuw50irl6m8e0diylhi6euhs9by3ssazl8x5bxhgzj',
          property: 'applicationID',
        },
      },
    },
    AkashaAppRelease: {
      source: { type: 'cid', required: true, immutable: false },
      version: { type: 'string', required: true, immutable: true, indexed: true },
      createdAt: { type: 'datetime', required: true, immutable: false, indexed: true },
      applicationID: { type: 'streamid', required: true, immutable: true, indexed: true },
      application: {
        type: 'view',
        viewType: 'relation',
        relation: {
          source: 'document',
          model: 'kjzl6hvfrbw6cb6pcdpdnrlau2rwz0gs5nddo3e5v578s4wstt2kpybrf11byzc',
          property: 'applicationID',
        },
      },
    },
    AkashaAppsStream: {
      active: { type: 'boolean', required: true, immutable: false, indexed: true },
      status: {
        type: 'reference',
        refType: 'enum',
        refName: 'AkashaAppsStreamModerationStatus',
        required: false,
        immutable: false,
        indexed: true,
      },
      createdAt: { type: 'datetime', required: true, immutable: false, indexed: true },
      moderationID: { type: 'streamid', required: false, immutable: false, indexed: true },
      applicationID: { type: 'streamid', required: true, immutable: true, indexed: true },
      application: {
        type: 'view',
        viewType: 'relation',
        relation: {
          source: 'document',
          model: 'kjzl6hvfrbw6cb6pcdpdnrlau2rwz0gs5nddo3e5v578s4wstt2kpybrf11byzc',
          property: 'applicationID',
        },
      },
    },
    AkashaBeam: {
      nsfw: { type: 'boolean', required: false, immutable: false, indexed: true },
      tags: {
        type: 'list',
        required: false,
        immutable: false,
        item: {
          type: 'reference',
          refType: 'object',
          refName: 'AkashaBeamLabeled',
          required: false,
          immutable: false,
        },
      },
      active: { type: 'boolean', required: true, immutable: false, indexed: true },
      content: {
        type: 'list',
        required: true,
        immutable: false,
        item: {
          type: 'reference',
          refType: 'object',
          refName: 'AkashaBeamBlockRecord',
          required: true,
          immutable: false,
        },
      },
      mentions: {
        type: 'list',
        required: false,
        immutable: false,
        item: { type: 'did', required: false, immutable: false },
      },
      createdAt: { type: 'datetime', required: true, immutable: false, indexed: true },
      embeddedStream: {
        type: 'reference',
        refType: 'object',
        refName: 'AkashaBeamEmbeddedType',
        required: false,
        immutable: false,
      },
      author: { type: 'view', viewType: 'documentAccount' },
      version: { type: 'view', viewType: 'documentVersion' },
      reflections: {
        type: 'view',
        viewType: 'relation',
        relation: {
          source: 'queryConnection',
          model: 'kjzl6hvfrbw6c9az8glxdc257r0tgzkjxj01nhwxilaciiidaxwafw4023wimnp',
          property: 'beamID',
        },
      },
      reflectionsCount: {
        type: 'view',
        viewType: 'relation',
        relation: {
          source: 'queryCount',
          model: 'kjzl6hvfrbw6c9az8glxdc257r0tgzkjxj01nhwxilaciiidaxwafw4023wimnp',
          property: 'beamID',
        },
      },
    },
    AkashaBeamBlockRecord: {
      order: { type: 'integer', required: true, immutable: false },
      blockID: { type: 'streamid', required: true, immutable: false },
    },
    AkashaBeamEmbeddedType: {
      label: { type: 'string', required: true, immutable: false },
      embeddedID: { type: 'streamid', required: true, immutable: false },
    },
    AkashaBeamLabeled: {
      value: { type: 'string', required: true, immutable: false },
      labelType: { type: 'string', required: true, immutable: false },
    },
    AkashaBeamStream: {
      active: { type: 'boolean', required: true, immutable: false, indexed: true },
      beamID: { type: 'streamid', required: true, immutable: true, indexed: true },
      status: {
        type: 'reference',
        refType: 'enum',
        refName: 'AkashaBeamStreamModerationStatus',
        required: false,
        immutable: false,
        indexed: true,
      },
      createdAt: { type: 'datetime', required: true, immutable: false, indexed: true },
      moderationID: { type: 'streamid', required: false, immutable: false, indexed: true },
      beam: {
        type: 'view',
        viewType: 'relation',
        relation: {
          source: 'document',
          model: 'kjzl6hvfrbw6c81jn00de1kfzdjtdbbivos4k3f17wa4a0u45c2v26d3j1eve68',
          property: 'beamID',
        },
      },
    },
    AkashaBlockStorage: {
      kind: {
        type: 'reference',
        refType: 'enum',
        refName: 'AkashaBlockStorageBlockStorageDef',
        required: false,
        immutable: false,
        indexed: true,
      },
      active: { type: 'boolean', required: true, immutable: false, indexed: true },
      blockID: { type: 'streamid', required: true, immutable: true },
      content: {
        type: 'list',
        required: true,
        immutable: false,
        item: {
          type: 'reference',
          refType: 'object',
          refName: 'AkashaBlockStorageLabeledValue',
          required: true,
          immutable: false,
        },
      },
      createdAt: { type: 'datetime', required: true, immutable: false, indexed: true },
      appVersionID: { type: 'streamid', required: true, immutable: false },
      block: {
        type: 'view',
        viewType: 'relation',
        relation: {
          source: 'document',
          model: 'kjzl6hvfrbw6c7in46qz14j69433lcmldlxqsyrxvayimxaqd62w7wnhkv2p4vd',
          property: 'blockID',
        },
      },
      author: { type: 'view', viewType: 'documentAccount' },
      version: { type: 'view', viewType: 'documentVersion' },
      appVersion: {
        type: 'view',
        viewType: 'relation',
        relation: {
          source: 'document',
          model: 'kjzl6hvfrbw6cb03csk8bxuw50irl6m8e0diylhi6euhs9by3ssazl8x5bxhgzj',
          property: 'appVersionID',
        },
      },
    },
    AkashaBlockStorageLabeledValue: {
      label: { type: 'string', required: true, immutable: false },
      value: { type: 'string', required: true, immutable: false },
      propertyType: { type: 'string', required: true, immutable: false },
    },
    AkashaContentBlock: {
      kind: {
        type: 'reference',
        refType: 'enum',
        refName: 'AkashaContentBlockBlockDef',
        required: false,
        immutable: false,
        indexed: true,
      },
      nsfw: { type: 'boolean', required: false, immutable: false, indexed: true },
      active: { type: 'boolean', required: true, immutable: false, indexed: true },
      content: {
        type: 'list',
        required: true,
        immutable: false,
        item: {
          type: 'reference',
          refType: 'object',
          refName: 'AkashaContentBlockLabeledValue',
          required: true,
          immutable: false,
        },
      },
      createdAt: { type: 'datetime', required: true, immutable: false, indexed: true },
      appVersionID: { type: 'streamid', required: true, immutable: false, indexed: true },
      author: { type: 'view', viewType: 'documentAccount' },
      version: { type: 'view', viewType: 'documentVersion' },
      appVersion: {
        type: 'view',
        viewType: 'relation',
        relation: {
          source: 'document',
          model: 'kjzl6hvfrbw6cb03csk8bxuw50irl6m8e0diylhi6euhs9by3ssazl8x5bxhgzj',
          property: 'appVersionID',
        },
      },
    },
    AkashaContentBlockLabeledValue: {
      label: { type: 'string', required: true, immutable: false },
      value: { type: 'string', required: true, immutable: false },
      propertyType: { type: 'string', required: true, immutable: false },
    },
    AkashaContentBlockStream: {
      active: { type: 'boolean', required: true, immutable: false, indexed: true },
      status: {
        type: 'reference',
        refType: 'enum',
        refName: 'AkashaContentBlockStreamModerationStatus',
        required: false,
        immutable: false,
        indexed: true,
      },
      blockID: { type: 'streamid', required: true, immutable: true, indexed: true },
      createdAt: { type: 'datetime', required: true, immutable: false, indexed: true },
      moderationID: { type: 'streamid', required: false, immutable: false, indexed: true },
      block: {
        type: 'view',
        viewType: 'relation',
        relation: {
          source: 'document',
          model: 'kjzl6hvfrbw6c7in46qz14j69433lcmldlxqsyrxvayimxaqd62w7wnhkv2p4vd',
          property: 'blockID',
        },
      },
    },
    AkashaFollow: {
      profileID: { type: 'streamid', required: true, immutable: true, indexed: true },
      isFollowing: { type: 'boolean', required: true, immutable: false, indexed: true },
      did: { type: 'view', viewType: 'documentAccount' },
      profile: {
        type: 'view',
        viewType: 'relation',
        relation: {
          source: 'document',
          model: 'kjzl6hvfrbw6c862oulkrdvxh2yfbhc997f7ahqtjppj2ejg8too3j7jmu8gsno',
          property: 'profileID',
        },
      },
    },
    AkashaIndexedStream: {
      active: { type: 'boolean', required: true, immutable: false, indexed: true },
      status: {
        type: 'reference',
        refType: 'enum',
        refName: 'AkashaIndexedStreamModerationStatus',
        required: false,
        immutable: false,
        indexed: true,
      },
      stream: { type: 'streamid', required: true, immutable: true, indexed: true },
      createdAt: { type: 'datetime', required: true, immutable: false, indexed: true },
      indexType: { type: 'string', required: true, immutable: true, indexed: true },
      indexValue: { type: 'string', required: true, immutable: true, indexed: true },
      streamType: {
        type: 'reference',
        refType: 'enum',
        refName: 'AkashaIndexedStreamStreamType',
        required: false,
        immutable: false,
        indexed: true,
      },
      moderationID: { type: 'streamid', required: false, immutable: false, indexed: true },
    },
    AkashaInterestsStream: {
      value: { type: 'string', required: true, immutable: true, indexed: true },
      active: { type: 'boolean', required: true, immutable: false, indexed: true },
      status: {
        type: 'reference',
        refType: 'enum',
        refName: 'AkashaInterestsStreamModerationStatus',
        required: false,
        immutable: false,
        indexed: true,
      },
      createdAt: { type: 'datetime', required: true, immutable: false, indexed: true },
      labelType: { type: 'string', required: true, immutable: true, indexed: true },
      moderationID: { type: 'streamid', required: false, immutable: false, indexed: true },
    },
    AkashaProfile: {
      name: { type: 'string', required: true, immutable: false, indexed: true },
      nsfw: { type: 'boolean', required: false, immutable: false, indexed: true },
      links: {
        type: 'list',
        required: false,
        immutable: false,
        item: {
          type: 'reference',
          refType: 'object',
          refName: 'AkashaProfileLinkSource',
          required: false,
          immutable: false,
        },
      },
      avatar: {
        type: 'reference',
        refType: 'object',
        refName: 'AkashaProfileImageVersions',
        required: false,
        immutable: false,
      },
      createdAt: { type: 'datetime', required: true, immutable: false, indexed: true },
      background: {
        type: 'reference',
        refType: 'object',
        refName: 'AkashaProfileImageVersions',
        required: false,
        immutable: false,
      },
      description: { type: 'string', required: false, immutable: false },
      did: { type: 'view', viewType: 'documentAccount' },
      followers: {
        type: 'view',
        viewType: 'relation',
        relation: {
          source: 'queryConnection',
          model: 'kjzl6hvfrbw6c5jg1zwrvbcvembp7v15kejrry05o2gvv2r4xghzfn2uluglus3',
          property: 'profileID',
        },
      },
      followersCount: {
        type: 'view',
        viewType: 'relation',
        relation: {
          source: 'queryCount',
          model: 'kjzl6hvfrbw6c5jg1zwrvbcvembp7v15kejrry05o2gvv2r4xghzfn2uluglus3',
          property: 'profileID',
        },
      },
    },
    AkashaProfileImageSource: {
      src: { type: 'uri', required: true, immutable: false },
      width: { type: 'integer', required: true, immutable: false },
      height: { type: 'integer', required: true, immutable: false },
    },
    AkashaProfileImageVersions: {
      default: {
        type: 'reference',
        refType: 'object',
        refName: 'AkashaProfileImageSource',
        required: true,
        immutable: false,
      },
      alternatives: {
        type: 'list',
        required: false,
        immutable: false,
        item: {
          type: 'reference',
          refType: 'object',
          refName: 'AkashaProfileImageSource',
          required: false,
          immutable: false,
        },
      },
    },
    AkashaProfileInterests: {
      topics: {
        type: 'list',
        required: true,
        immutable: false,
        item: {
          type: 'reference',
          refType: 'object',
          refName: 'AkashaProfileInterestsLabeled',
          required: true,
          immutable: false,
        },
      },
      did: { type: 'view', viewType: 'documentAccount' },
    },
    AkashaProfileInterestsLabeled: {
      value: { type: 'string', required: true, immutable: false },
      labelType: { type: 'string', required: true, immutable: false },
    },
    AkashaProfileLinkSource: {
      href: { type: 'uri', required: true, immutable: false },
      label: { type: 'string', required: false, immutable: false },
    },
    AkashaProfileStream: {
      active: { type: 'boolean', required: true, immutable: false, indexed: true },
      status: {
        type: 'reference',
        refType: 'enum',
        refName: 'AkashaProfileStreamModerationStatus',
        required: false,
        immutable: false,
        indexed: true,
      },
      createdAt: { type: 'datetime', required: true, immutable: false, indexed: true },
      profileID: { type: 'streamid', required: true, immutable: true, indexed: true },
      moderationID: { type: 'streamid', required: false, immutable: false, indexed: true },
      profile: {
        type: 'view',
        viewType: 'relation',
        relation: {
          source: 'document',
          model: 'kjzl6hvfrbw6c862oulkrdvxh2yfbhc997f7ahqtjppj2ejg8too3j7jmu8gsno',
          property: 'profileID',
        },
      },
    },
    AkashaReflect: {
      nsfw: { type: 'boolean', required: false, immutable: false, indexed: true },
      tags: {
        type: 'list',
        required: false,
        immutable: false,
        item: { type: 'string', required: false, immutable: false },
      },
      active: { type: 'boolean', required: true, immutable: false, indexed: true },
      beamID: { type: 'streamid', required: true, immutable: false },
      content: {
        type: 'list',
        required: true,
        immutable: false,
        item: {
          type: 'reference',
          refType: 'object',
          refName: 'AkashaReflectProviderValue',
          required: true,
          immutable: false,
        },
      },
      isReply: { type: 'boolean', required: false, immutable: false, indexed: true },
      mentions: {
        type: 'list',
        required: false,
        immutable: false,
        item: { type: 'streamid', required: false, immutable: false },
      },
      createdAt: { type: 'datetime', required: true, immutable: false, indexed: true },
      reflection: { type: 'streamid', required: false, immutable: false, indexed: true },
      beam: {
        type: 'view',
        viewType: 'relation',
        relation: {
          source: 'document',
          model: 'kjzl6hvfrbw6c81jn00de1kfzdjtdbbivos4k3f17wa4a0u45c2v26d3j1eve68',
          property: 'beamID',
        },
      },
      author: { type: 'view', viewType: 'documentAccount' },
      version: { type: 'view', viewType: 'documentVersion' },
    },
    AkashaReflectProviderValue: {
      label: { type: 'string', required: true, immutable: false },
      value: { type: 'string', required: true, immutable: false },
      propertyType: { type: 'string', required: true, immutable: false },
    },
    AkashaReflectStream: {
      active: { type: 'boolean', required: true, immutable: false, indexed: true },
      beamID: { type: 'streamid', required: true, immutable: false, indexed: true },
      status: {
        type: 'reference',
        refType: 'enum',
        refName: 'AkashaReflectStreamModerationStatus',
        required: false,
        immutable: false,
        indexed: true,
      },
      createdAt: { type: 'datetime', required: true, immutable: false, indexed: true },
      moderationID: { type: 'streamid', required: false, immutable: false, indexed: true },
      reflectionID: { type: 'streamid', required: true, immutable: true, indexed: true },
      reflection: {
        type: 'view',
        viewType: 'relation',
        relation: {
          source: 'document',
          model: 'kjzl6hvfrbw6c9az8glxdc257r0tgzkjxj01nhwxilaciiidaxwafw4023wimnp',
          property: 'reflectionID',
        },
      },
    },
  },
  enums: {
    AkashaAppApplicationType: ['APP', 'PLUGIN', 'WIDGET', 'OTHER'],
    AkashaAppsStreamModerationStatus: ['REMOVED', 'IN_REVIEW', 'SUSPENDED', 'NSFW', 'OK', 'OTHER'],
    AkashaBeamStreamModerationStatus: ['REMOVED', 'IN_REVIEW', 'SUSPENDED', 'NSFW', 'OK', 'OTHER'],
    AkashaBlockStorageBlockStorageDef: ['TEXT', 'BOOL', 'EMOJI', 'FORM_DATA', 'OTHER'],
    AkashaContentBlockBlockDef: ['TEXT', 'FORM', 'OTHER'],
    AkashaContentBlockStreamModerationStatus: [
      'REMOVED',
      'IN_REVIEW',
      'SUSPENDED',
      'NSFW',
      'OK',
      'OTHER',
    ],
    AkashaIndexedStreamModerationStatus: [
      'REMOVED',
      'IN_REVIEW',
      'SUSPENDED',
      'NSFW',
      'OK',
      'OTHER',
    ],
    AkashaIndexedStreamStreamType: [
      'BEAM',
      'REFLECT',
      'PROFILE',
      'APP',
      'EXTENSION',
      'PLUGIN',
      'WIDGET',
      'OTHER',
    ],
    AkashaInterestsStreamModerationStatus: [
      'REMOVED',
      'IN_REVIEW',
      'SUSPENDED',
      'NSFW',
      'OK',
      'OTHER',
    ],
    AkashaProfileStreamModerationStatus: [
      'REMOVED',
      'IN_REVIEW',
      'SUSPENDED',
      'NSFW',
      'OK',
      'OTHER',
    ],
    AkashaReflectStreamModerationStatus: [
      'REMOVED',
      'IN_REVIEW',
      'SUSPENDED',
      'NSFW',
      'OK',
      'OTHER',
    ],
  },
  accountData: {
    akashaApp: { type: 'set', name: 'AkashaApp' },
    akashaAppList: { type: 'connection', name: 'AkashaApp' },
    akashaAppRelease: { type: 'set', name: 'AkashaAppRelease' },
    akashaAppReleaseList: { type: 'connection', name: 'AkashaAppRelease' },
    akashaAppsStream: { type: 'set', name: 'AkashaAppsStream' },
    akashaAppsStreamList: { type: 'connection', name: 'AkashaAppsStream' },
    akashaBeamList: { type: 'connection', name: 'AkashaBeam' },
    akashaBeamStream: { type: 'set', name: 'AkashaBeamStream' },
    akashaBeamStreamList: { type: 'connection', name: 'AkashaBeamStream' },
    akashaBlockStorage: { type: 'set', name: 'AkashaBlockStorage' },
    akashaBlockStorageList: { type: 'connection', name: 'AkashaBlockStorage' },
    akashaContentBlockList: { type: 'connection', name: 'AkashaContentBlock' },
    akashaContentBlockStream: { type: 'set', name: 'AkashaContentBlockStream' },
    akashaContentBlockStreamList: { type: 'connection', name: 'AkashaContentBlockStream' },
    akashaFollow: { type: 'set', name: 'AkashaFollow' },
    akashaFollowList: { type: 'connection', name: 'AkashaFollow' },
    akashaIndexedStream: { type: 'set', name: 'AkashaIndexedStream' },
    akashaIndexedStreamList: { type: 'connection', name: 'AkashaIndexedStream' },
    akashaInterestsStream: { type: 'set', name: 'AkashaInterestsStream' },
    akashaInterestsStreamList: { type: 'connection', name: 'AkashaInterestsStream' },
    akashaProfile: { type: 'node', name: 'AkashaProfile' },
    akashaProfileInterests: { type: 'node', name: 'AkashaProfileInterests' },
    akashaProfileStream: { type: 'set', name: 'AkashaProfileStream' },
    akashaProfileStreamList: { type: 'connection', name: 'AkashaProfileStream' },
    akashaReflectList: { type: 'connection', name: 'AkashaReflect' },
    akashaReflectStream: { type: 'set', name: 'AkashaReflectStream' },
    akashaReflectStreamList: { type: 'connection', name: 'AkashaReflectStream' },
  },
};
