export const actionTypes = {
  GET_PROFILES: 'GET_PROFILES',
  GET_MORE_PROFILES: 'GET_MORE_PROFILES',
  GET_APPS: 'GET_APPS',
  GET_MORE_APPS: 'GET_MORE_APPS',
  CHANGE_PROFILES_FILTER: 'CHANGE_PROFILES_FILTER',
  CHANGE_APPS_FILTER: 'CHANGE_APPS_FILTER',
  CLEANUP: 'CLEANUP',
};
