export const actionTypes = {
  GET_LOGGED_PROFILE: 'GET_LOGGED_PROFILE',
  GET_PROFILES: 'GET_PROFILES',
  GET_PROFILE_FOLLOWERS: 'GET_PROFILE_FOLLOWERS',
  GET_PROFILE_FOLLOWINGS: 'GET_PROFILE_FOLLOWINGS',
  GET_MORE_PROFILES: 'GET_MORE_PROFILES',
  GET_APPS: 'GET_APPS',
  GET_MORE_APPS: 'GET_MORE_APPS',
  CHANGE_PROFILES_FILTER: 'CHANGE_PROFILES_FILTER',
  CHANGE_APPS_FILTER: 'CHANGE_APPS_FILTER',
  CLEANUP: 'CLEANUP',
};
