name: deploy staging ethereum.world api

on:
  push:
    branches:
      - next
    paths:
      - '.github/workflows/**'
      - 'api/**'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh deployment
        uses: appleboy/ssh-action@v0.1.4
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.SSHKEY }}
          script: |
            cd apps/akasha-world-framework
            git checkout next
            git pull
            cd api/hub
            docker-compose down
            docker-compose build --no-cache
            docker-compose up -d
