name: W3S publish staging
on:
  push:
    branches:
      - next
#  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: corepack enable
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
          cache-dependency-path: yarn.lock
      - run: node --version
      - name: Get Secrets
        uses: bitwarden/sm-action@v2
        with:
          access_token: ${{ secrets.BW_ACCESS_TOKEN }}
          secrets: |
            470c7a84-3010-485a-a5e9-b1cb00bdfc15 > W3_STORAGE_DELEGATE
      - name: install root dependencies
        env:
          CI: 1
          NODE_ENV: production
          PUBLIC_LOG_LEVEL: warn
          PUBLIC_WALLET_CONNECT_PROJECT_ID: ${{ secrets.PUBLIC_WALLET_CONNECT_PROJECT_ID }}
          PUBLIC_API_STATUS_PATH: ${{ secrets.PUBLIC_API_STATUS_PATH }}
          PUBLIC_CERAMIC_API_ENDPOINT: ${{ secrets.PUBLIC_CERAMIC_API_ENDPOINT }}
          PUBLIC_GRAPHQL_URI: ${{ secrets.PUBLIC_GRAPHQL_URI }}
          PUBLIC_INDEXING_DID: ${{ secrets.PUBLIC_INDEXING_DID }}
          PUBLIC_W3_STORAGE_DELEGATE_BASE_URL: ${{ secrets.PUBLIC_W3_STORAGE_DELEGATE_BASE_URL }}
          INFURA_ID: ${{ secrets.INFURA_ID }}
          INFURA_IPFS_ID: ${{ secrets.INFURA_IPFS_ID }}
          INFURA_IPFS_SECRET: ${{ secrets.INFURA_IPFS_SECRET }}
          MATOMO_SITE_ID: ${{ secrets.MATOMO_SITE_ID }}
          MATOMO_TRACKER_URL: ${{ secrets.MATOMO_TRACKER_URL }}
        run: |
          yarn install --immutable
          yarn build:all
      - run: echo "${GITHUB_WORKSPACE}/node_modules/.bin" >> $GITHUB_PATH
      - uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: "next"
      - name: Set the affected projects
        id: affected-projects
        run: |
          echo "AFFECTED_EXTENSIONS=$(nx show projects --affected --json --type app)" >> "$GITHUB_OUTPUT"
      - run: nx affected -t prepare build
      - name: Upload extensions
        env:
          CI: 1
          AFFECTED_EXTENSIONS: ${{ steps.affected-projects.outputs.AFFECTED_EXTENSIONS }}
          NODE_ENV: production
          PUBLIC_LOG_LEVEL: warn
          PUBLIC_WALLET_CONNECT_PROJECT_ID: ${{ secrets.PUBLIC_WALLET_CONNECT_PROJECT_ID }}
          PUBLIC_API_STATUS_PATH: ${{ secrets.PUBLIC_API_STATUS_PATH }}
          PUBLIC_CERAMIC_API_ENDPOINT: ${{ secrets.PUBLIC_CERAMIC_API_ENDPOINT }}
          PUBLIC_GRAPHQL_URI: ${{ secrets.PUBLIC_GRAPHQL_URI }}
          PUBLIC_INDEXING_DID: ${{ secrets.PUBLIC_INDEXING_DID }}
          PUBLIC_W3_STORAGE_DELEGATE_BASE_URL: ${{ secrets.PUBLIC_W3_STORAGE_DELEGATE_BASE_URL }}
          W3_STORAGE_DID_KEY: ${{ secrets.W3_STORAGE_DID_KEY }}
          W3_STORAGE_DELEGATE: ${{ env.W3_STORAGE_DELEGATE }}
          DID_PUBLISHER_PRIVATE_KEY: ${{ secrets.DID_PUBLISHER_PRIVATE_KEY }}
        run: yarn run extensions:upload
      - name: Trigger update message
        run: |
          curl ${{secrets.WEBHOOK_BOT_STAGING}}
