name: W3S publish staging
on:
  push:
    branches:
      - next
#  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: corepack enable
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
          cache-dependency-path: yarn.lock
      - run: node --version
      - name: Get Secrets
        uses: bitwarden/sm-action@v2
        with:
          access_token: ${{ secrets.BW_ACCESS_TOKEN }}
          secrets: |
            f30aabba-7950-4054-94c5-b1ce00f4cb50 > PUBLIC_WALLET_CONNECT_PROJECT_ID
            17ecfb19-42db-40e6-8e17-b1ce00f666df > PUBLIC_API_STATUS_PATH
            d8af3b9d-7907-4221-bdf6-b1ce00f5e03e > PUBLIC_CERAMIC_API_ENDPOINT
            d62a4dc9-ea81-4e0d-a501-b1ce00f610e9 > PUBLIC_GRAPHQL_URI
            9ca0c09c-4bcd-475b-a2bd-b1ce00f51cc1 > PUBLIC_INDEXING_DID
            7b117280-03f9-4905-b5d9-b1ce00f63a4a > PUBLIC_W3_STORAGE_DELEGATE_BASE_URL
            470c7a84-3010-485a-a5e9-b1cb00bdfc15 > W3_STORAGE_DELEGATE
            a73b98f3-82b5-4db3-9c33-b1cb00c1318d > W3_STORAGE_DID_KEY
            dea73509-ff81-48b9-9d75-b1cb00c0b426 > DID_PUBLISHER_PRIVATE_KEY
            05aebf31-a067-48f7-ab02-b1ce01311d4c > WEBHOOK_BOT_STAGING

      - name: install root dependencies
        env:
          CI: 1
          NODE_ENV: production
          PUBLIC_LOG_LEVEL: warn
          PUBLIC_WALLET_CONNECT_PROJECT_ID: ${{ env.PUBLIC_WALLET_CONNECT_PROJECT_ID }}
          PUBLIC_API_STATUS_PATH: ${{ env.PUBLIC_API_STATUS_PATH }}
          PUBLIC_CERAMIC_API_ENDPOINT: ${{ env.PUBLIC_CERAMIC_API_ENDPOINT }}
          PUBLIC_GRAPHQL_URI: ${{ env.PUBLIC_GRAPHQL_URI }}
          PUBLIC_INDEXING_DID: ${{ env.PUBLIC_INDEXING_DID }}
          PUBLIC_W3_STORAGE_DELEGATE_BASE_URL: ${{ env.PUBLIC_W3_STORAGE_DELEGATE_BASE_URL }}
          INFURA_ID: ${{ secrets.INFURA_ID }}
          INFURA_IPFS_ID: ${{ secrets.INFURA_IPFS_ID }}
          INFURA_IPFS_SECRET: ${{ secrets.INFURA_IPFS_SECRET }}
          MATOMO_SITE_ID: ${{ secrets.MATOMO_SITE_ID }}
          MATOMO_TRACKER_URL: ${{ secrets.MATOMO_TRACKER_URL }}
        run: |
          yarn install --immutable
          yarn build:all
      - run: echo "${GITHUB_WORKSPACE}/node_modules/.bin" >> $GITHUB_PATH
      - uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: "next"
      - name: Set the affected projects
        id: affected-projects
        run: |
          echo "AFFECTED_EXTENSIONS=$(nx show projects --affected --json --type app)" >> "$GITHUB_OUTPUT"
      - run: nx affected -t prepare build
      - name: Upload extensions
        env:
          CI: 1
          AFFECTED_EXTENSIONS: ${{ steps.affected-projects.outputs.AFFECTED_EXTENSIONS }}
          NODE_ENV: production
          PUBLIC_LOG_LEVEL: warn
          PUBLIC_WALLET_CONNECT_PROJECT_ID: ${{ env.PUBLIC_WALLET_CONNECT_PROJECT_ID }}
          PUBLIC_API_STATUS_PATH: ${{ env.PUBLIC_API_STATUS_PATH }}
          PUBLIC_CERAMIC_API_ENDPOINT: ${{ env.PUBLIC_CERAMIC_API_ENDPOINT }}
          PUBLIC_GRAPHQL_URI: ${{ env.PUBLIC_GRAPHQL_URI }}
          PUBLIC_INDEXING_DID: ${{ env.PUBLIC_INDEXING_DID }}
          PUBLIC_W3_STORAGE_DELEGATE_BASE_URL: ${{ env.PUBLIC_W3_STORAGE_DELEGATE_BASE_URL }}
          W3_STORAGE_DID_KEY: ${{ env.W3_STORAGE_DID_KEY }}
          W3_STORAGE_DELEGATE: ${{ env.W3_STORAGE_DELEGATE }}
          DID_PUBLISHER_PRIVATE_KEY: ${{ env.DID_PUBLISHER_PRIVATE_KEY }}
        run: yarn run extensions:upload
      - name: Trigger update message
        run: |
          curl ${{env.WEBHOOK_BOT_STAGING}}
