fragment AkashaAppFragmentM on AkashaApp{
  id
  applicationType
  description
  license
  name
  displayName
  keywords
  releases(first: 5, sorting: {createdAt: DESC} ){
    edges {
      node {
        id
        createdAt
        source
        version
      }
      cursor
    }
  }
  releasesCount
  author {
    id
    isViewer
    akashaProfile {
      ...UserProfileFragmentM
    }
  }
  contributors {
    id
    isViewer
    akashaProfile {
      ...UserProfileFragmentM
    }
  }
}

fragment AppReleaseFragmentM on AkashaAppRelease{
  application {
    ...AkashaAppFragmentM
  }
  applicationID
  id
  source
  version
  createdAt
}

mutation SetAppRelease($i: SetAkashaAppReleaseInput!){
  setAkashaAppRelease(input: $i){
    document {
      ...AppReleaseFragmentM
    }
    clientMutationId
  }
}


mutation UpdateAppRelease($i: UpdateAkashaAppReleaseInput!){
  updateAkashaAppRelease(input: $i){
    document {
      ...AppReleaseFragmentM
    }
    clientMutationId
  }
}

mutation CreateApp($i: SetAkashaAppInput!){
  setAkashaApp(input: $i){
    document {
      ...AkashaAppFragmentM
    }
    clientMutationId
  }
}

mutation UpdateApp($i: UpdateAkashaAppInput!){
  updateAkashaApp(input: $i){
    document {
      ...AkashaAppFragmentM
    }
    clientMutationId
  }
}

fragment AkashaWorldFragmentM on AkashaWorld{
  id
  icon {
    default {
      sizes
      src
      width
      height
    }
  }
  active
  name
  instanceURL
  createdAt
  creator {
    id
  }
  extensionPublishers {
    id
    akashaProfile {
      name
      id
      avatar {
        default {
          src
          width
          height
        }
      }
    }
  }
}

fragment AkashaWorldConfigM on AkashaWorldConfig{
  id
  worldID
  creator {
    id
  }
  active
  createdAt
  homepageExtension
  registryExtension
  layoutExtension

}

fragment AkashaWorldConfigExtensionM on AkashaWorldConfigExtension{
  id
  active
  createdAt
  worldConfigID
  extensionID
  extension {
    name
    displayName
    author {
      id
    }
    logoImage {
      src
      width
      height
    }
  }
  creator {
    id
  }
}

mutation CreateWorld($i: SetAkashaWorldInput!){
  setAkashaWorld(input: $i){
    document {
      ...AkashaWorldFragmentM
    }
    clientMutationId
  }
}

mutation UpdateWorld($i: UpdateAkashaWorldInput!){
  updateAkashaWorld(input: $i){
    document {
      ...AkashaWorldFragmentM
    }
    clientMutationId
  }
}

mutation CreateAkashaWorldConfig($i: SetAkashaWorldConfigInput!){
  setAkashaWorldConfig(input: $i){
    document {
      ...AkashaWorldConfigM
    }
    clientMutationId
  }
}

mutation UpdateAkashaWorldConfig($i: UpdateAkashaWorldConfigInput!){
  updateAkashaWorldConfig(input: $i){
    document {
      ...AkashaWorldConfigM
    }
    clientMutationId
  }
}

mutation CreateAkashaWorldConfigExtension($i: SetAkashaWorldConfigExtensionInput!){
  setAkashaWorldConfigExtension(input: $i){
    document {
      ...AkashaWorldConfigExtensionM
    }
    clientMutationId
  }
}

mutation UpdateAkashaWorldConfigExtension($i: UpdateAkashaWorldConfigExtensionInput!){
  updateAkashaWorldConfigExtension(input: $i){
    document {
      ...AkashaWorldConfigExtensionM
    }
    clientMutationId
  }
}

mutation DeleteAkashaWorldConfigExtension($i: EnableIndexingAkashaWorldConfigExtensionInput!){
  enableIndexingAkashaWorldConfigExtension(input: $i){
    clientMutationId
  }
}

fragment AkashaWorldMetaInfoM on AkashaWorldMetaInfo{
  id
  socialLinks {
    name
    href
  }
  worldID
  keywords
  description
  guidelinesUrl
}

mutation CreateAkashaWorldMetaInfo($i: SetAkashaWorldMetaInfoInput!){
  setAkashaWorldMetaInfo(input: $i){
    document {
      ...AkashaWorldMetaInfoM
    }
    clientMutationId
  }
}

mutation UpdateAkashaWorldMetaInfo($i: UpdateAkashaWorldMetaInfoInput!){
  updateAkashaWorldMetaInfo(input: $i){
    document {
      ...AkashaWorldMetaInfoM
    }
    clientMutationId
  }
}

mutation DeleteAkashaWorldMetaInfo($i: EnableIndexingAkashaWorldMetaInfoInput!){
  enableIndexingAkashaWorldMetaInfo(input: $i){
    clientMutationId
  }
}

