fragment AkashaAppFragment on AkashaApp{
  id
  applicationType
  description
  license
  name
  displayName
  keywords
  nsfw
  createdAt
  releases(first: 5, sorting: {createdAt: DESC} ){
    edges {
      node {
        id
        createdAt
        source
        version
        meta {
          property
          provider
          value
        }
      }
      cursor
    }
  }
  releasesCount
  author {
    id
    isViewer
    akashaProfile {
      ...UserProfileFragment
    }
  }
  logoImage {
    height
    width
    src
  }
  coverImage {
    height
    width
    src
  }
  gallery {
    height
    width
    src
  }
  links {
    href
    label
  }
  contributors {
    id
    isViewer
    akashaProfile {
      ...UserProfileFragment
    }
  }
  meta {
    property
    provider
    value
  }
}

fragment AppReleaseFragment on AkashaAppRelease{
  application {
    ...AkashaAppFragment
  }
  applicationID
  id
  source
  version
  createdAt
  meta {
    provider
    property
    value
  }
}

query GetApps($after: String, $before: String, $first: Int, $last: Int, $filters: AkashaAppFiltersInput, $sorting: AkashaAppSortingInput){
  akashaAppIndex(after: $after, before: $before, first: $first, last: $last, filters: $filters, sorting:  $sorting){
    edges {
      node {
        ...AkashaAppFragment
      }
      cursor
    }
    pageInfo {
      startCursor
      endCursor
      hasNextPage
      hasPreviousPage
    }
  }
}

query GetAppsStream($indexer: ID!, $after: String, $before: String, $first: Int, $last: Int, $filters: AkashaAppsStreamFiltersInput, $sorting: AkashaAppsStreamSortingInput){
  node(id: $indexer){
    ... on CeramicAccount{
      akashaAppsStreamList(after: $after, before: $before, first: $first, last: $last, filters: $filters, sorting:  $sorting){
        edges {
          node {
            moderationID
            active
            applicationID
            status
            createdAt
          }
          cursor
        }
        pageInfo {
          startCursor
          endCursor
          hasNextPage
          hasPreviousPage
        }
      }
    }
  }
}

query GetAppsByID($id: ID!) {
  node(id: $id) {
    ...on AkashaApp {
      ...AkashaAppFragment
    }
  }
}

query GetAppsByPublisherDID($id: ID!, $after: String, $before: String, $first: Int, $last: Int, $filters: AkashaAppFiltersInput, $sorting: AkashaAppSortingInput) {
  node(id: $id) {
    ...on CeramicAccount {
      akashaAppList(after: $after, before: $before, first: $first, last: $last, filters: $filters, sorting:  $sorting){
        edges {
          node {
            ...AkashaAppFragment
          }
          cursor
        }
        pageInfo {
          startCursor
          endCursor
          hasNextPage
          hasPreviousPage
        }
      }
    }
  }
}

query GetAppsReleasesByPublisherDID($id: ID!, $after: String, $before: String, $first: Int, $last: Int, $filters: AkashaAppReleaseFiltersInput, $sorting: AkashaAppReleaseSortingInput) {
  node(id: $id) {
    ...on CeramicAccount {
      akashaAppReleaseList(after: $after, before: $before, first: $first, last: $last, filters: $filters, sorting:  $sorting){
        edges {
          node {
            ...AppReleaseFragment
          }
          cursor
        }
        pageInfo {
          startCursor
          endCursor
          hasNextPage
          hasPreviousPage
        }
      }
    }
  }
}

query GetAppsReleases($after: String, $before: String, $first: Int, $last: Int, $filters: AkashaAppReleaseFiltersInput, $sorting: AkashaAppReleaseSortingInput){
  akashaAppReleaseIndex(after: $after, before: $before, first: $first, last: $last, filters:  $filters, sorting: $sorting){
    edges {
      node {
        ...AppReleaseFragment
      }
      cursor
    }
    pageInfo {
      startCursor
      endCursor
      hasNextPage
      hasPreviousPage
    }
  }
}

query GetAppReleaseByID($id: ID!) {
  node(id: $id) {
    ...on AkashaAppRelease {
      ...AppReleaseFragment
    }
  }
}


fragment AkashaWorldFragment on AkashaWorld{
  id
  icon {
    default {
      sizes
      src
      width
      height
    }
  }
  active
  instanceURL
  createdAt
  creator {
    id
  }
  extensionPublishers {
    id
    akashaProfile {
      name
      id
      avatar {
        default {
          src
          width
          height
        }
      }
    }
  }
}

fragment AkashaWorldConfigFragment on AkashaWorldConfig{
  id
  worldID
  creator {
    id
  }
  active
  createdAt
  homepageExtension
  registryExtension
  layoutExtension
}

fragment AkashaWorldConfigExtensionFragment on AkashaWorldConfigExtension{
  id
  active
  createdAt
  worldConfigID
  extensionID
  extension {
    name
    displayName
    author {
      id
    }
    logoImage {
      src
      width
      height
    }
  }
  creator {
    id
  }
}

query GetWorldByID($id: ID!) {
  node(id: $id){
    ... on AkashaWorld {
      ...AkashaWorldFragment
    }
  }
}

query GetWorldByName($name: String!) {
 akashaWorldIndex(first: 2, filters: {and: [{where: {name: {equalTo: $name}}}, {where: {active: {equalTo: true}}}]}) {
   edges {
     node {
       ...AkashaWorldFragment
     }
   }
 }
}

query GetWorldConfig($worldID: String!, $creator: ID){
 akashaWorldConfigIndex(first: 1, filters: {and: [{where: {worldID: {equalTo: $worldID}}}, {where: {active: {equalTo: true}}}]}){
   edges {
     node {
      ...AkashaWorldConfigFragment
       extensions(account:  $creator, first: 100){
         edges {
           node {
             ...AkashaWorldConfigExtensionFragment
           }
         }
       }
     }
   }
 }
}

query GetWorldConfigByID($configID: ID!){
  node(id: $configID){
    ... on AkashaWorldConfig {
      ...AkashaWorldConfigFragment
    }
  }
}

query GetWorldConfigExtensions($configID: String!){
 akashaWorldConfigExtensionIndex(first: 100, filters: {and: [{where: {worldConfigID: {equalTo: $configID}}}, {where: {active: {equalTo: true}}}]}) {
   edges {
     node {
       ...AkashaWorldConfigExtensionFragment
     }
   }
 }
}

query GetWorldFullInfo($id: ID!, $creator: ID){
  node(id: $id){
    ... on AkashaWorld {
      ...AkashaWorldFragment
      metaInfo(first: 1, account: $creator){
        edges {
          node {
            description
            id
            guidelinesUrl
            socialLinks {
              href
              name
            }
            keywords
            worldID
          }
        }
      }
      configInfo(first: 1, filters: {and: [{where: {active: {equalTo: true}}}]}, account: $creator){
        edges {
          node {
           ...AkashaWorldConfigFragment
          }
        }
      }
    }
  }
}
